import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{ts,tsx}'],
	theme: {
		extend: {},
		// fontSize: {
		// 	xs: ['10px', { lineHeight: '16px' }],
		// 	sm: ['12px', { lineHeight: '16px' }],
		// 	base: ['14px', { lineHeight: '20px' }],
		// 	lg: ['16px', { lineHeight: '24px' }],
		// 	xl: ['18px', { lineHeight: '28px' }],
		// 	'2xl': ['20px', { lineHeight: '28px' }],
		// 	'3xl': ['24px', { lineHeight: '32px' }],
		// 	'4xl': ['30px', { lineHeight: '36px' }],
		// 	'5xl': ['36px', { lineHeight: '40px' }],
		// 	'6xl': ['48px', { lineHeight: '1' }],
		// 	'7xl': ['60px', { lineHeight: '1' }],
		// 	'8xl': ['72px', { lineHeight: '1' }],
		// 	'9xl': ['96px', { lineHeight: '1' }],
		// 	'10xl': ['128px', { lineHeight: '1' }],
		// },
		// spacing: {
		// 	px: '1px',
		// 	0: '0px',
		// 	0.5: '2px',
		// 	1: '4px',
		// 	1.5: '6px',
		// 	2: '8px',
		// 	2.5: '10px',
		// 	3: '12px',
		// 	3.5: '14px',
		// 	4: '16px',
		// 	5: '20px',
		// 	6: '24px',
		// 	7: '28px',
		// 	8: '32px',
		// 	9: '36px',
		// 	10: '40px',
		// 	11: '44px',
		// 	12: '48px',
		// 	14: '56px',
		// 	16: '64px',
		// 	20: '80px',
		// 	24: '96px',
		// 	28: '112px',
		// 	32: '128px',
		// 	36: '144px',
		// 	40: '160px',
		// 	44: '176px',
		// 	48: '192px',
		// 	52: '208px',
		// 	56: '224px',
		// 	60: '240px',
		// 	64: '256px',
		// 	72: '288px',
		// 	80: '320px',
		// 	96: '384px',
		// },
		colors: {
			primary: {
				DEFAULT: 'rgb(var(--primary))',
				fg: 'rgb(var(--primary-fg))',
			},
			secondary: {
				DEFAULT: 'rgb(var(--secondary))',
				fg: 'rgb(var(--secondary-fg))',
			},
			hinted: {
				DEFAULT: 'rgb(var(--hinted))',
				fg: 'rgb(var(--hinted-fg))',
			},
			muted: {
				DEFAULT: 'rgb(var(--muted))',
				fg: 'rgb(var(--muted-fg))',
			},
			input: 'rgb(var(--input))',
			divider: 'rgb(var(--divider))',
		},
		fontFamily: {
			sans: `"Roboto", ui-sans-serif, sans-serif`,
			mono: `"JetBrains Mono NL", ui-monospace, monospace`,
		},
	},
	plugins: [
		// forms(),
	],
};
